### ISSUE TITLE
Signal generator automatically starts

### ISSUE THREAD

**Issue by pesky-cpu** [TOSUN-Shanghai/TSMaster#30] opened 2021-12-10 19:19 UTC
**Bug:** The message signal generator automatically starts when going online on the bus. This can be dangerous if the signal is to command a motor rpm, etc.
![image](https://user-images.githubusercontent.com/27743747/145629662-70447f73-73ab-41d9-883a-d62a4d84768d.png)

**Comment by freshhope** [comment] 2021-12-11 23:54
The signal generator will never automatically transmit any message until "auto start" checkbox is checked:
![image](https://user-images.githubusercontent.com/16358754/145695239-6b27c048-d3a8-4e77-8fd4-0cedeaa226f2.png)

and the following signal generators will only be active after their parent message is being transmitted:
![image](https://user-images.githubusercontent.com/16358754/145695251-81ab415d-bf98-4b70-8010-3f92667f656e.png)

If you do not want to auto send messages on application connected, please uncheck the auto start icon on top right area to disable auto start.

The default auto send behavior of newly created transmit window is disabled.

**Comment by pesky-cpu** [comment] 2021-12-13 18:37
The above configuration was automatically transmitting with the 'auto start' unchecked. Can you confirm that it looks correct for not transmitting?

![image](https://user-images.githubusercontent.com/27743747/145869067-5c8136d6-36a6-4d8e-8b48-a29202679233.png)

**Comment by freshhope** [comment] 2021-12-13 23:48
It looks correct, I can confirm the automatically transmitted message is not from this transmit window, it may be from RBS (remaining bus simulation), or mini program (configured for auto start), or online replay module (configure for auto start), and many other potential components, could you please check the following information to see which auto start modules are currently being used:

![image](https://user-images.githubusercontent.com/16358754/145906991-e5c18683-3543-4831-af2a-c3d6dc9b0c21.png)

**Comment by pesky-cpu** [comment] 2021-12-13 23:54
Not seeing any autostart modules on this configuration

![image](https://user-images.githubusercontent.com/27743747/145907651-9564a2c1-9556-4692-9c13-495274683295.png)

**Comment by freshhope** [comment] 2021-12-14 00:17
Yes, so could you take a screenshot of both CAN transmit and CAN trace to see which messages are marked as transmit ?

**Comment by freshhope** [comment] 2022-01-17 01:03
closed due to no evidence, reopen if reproduction is possible.

**Closed by freshhope** 2022-01-17 01:03 UTC
